# Generated by Django 3.2.2 on 2021-05-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('display_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
