# Generated by Django 3.2.2 on 2021-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_image',
            field=models.ImageField(blank=True, default='', upload_to='shop/images'),
        ),
    ]
