# Generated by Django 3.2.2 on 2021-05-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_display_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='shop/images'),
        ),
    ]
